### PR TITLE
Update to Pulsar 2.11.0

### PR DESCRIPTION
**Pull request by cbornet**
### Documentation

  - Does this pull request introduce a new feature? no
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)
  - If a feature is not applicable for documentation, explain why?
  - If a feature is not documented yet in this PR, please create a followup issue for adding the documentation

### CODE REVIEW

**Review by eolivelli — APPROVED** [review]
LGTM

**Comment by eolivelli** [comment]
LGTM as far as we fix the build issues :-) 

```
Error:  Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project pulsar-spark: Compilation failure
Error:  /home/runner/work/pulsar-adapters/pulsar-adapters/pulsar-spark/src/main/java/org/apache/pulsar/spark/SparkStreamingPulsarReceiver.java:[41,7] error: cannot access Serializable
Error:    class file for scala.Serializable not found
Error:  -> [Help 1]
```

**Comment by cbornet** [comment]
That's weird. It compiles fine on my machine...
The Spark version used is very old and there could be an incompatibility with JDK17

**Comment by cbornet** [comment]
It seems that if we update Scala, it works for Spark but not for the kafka 0.8 client wrapper.
The Kafka 0.8 client wrapper is very old, depends on a very old scala version (2.9), only works as replacement for 0.8.1.1 and for instance not for 0.8.2.0.
I don't have context for this lib so I'm not sure what to do. Should we drop support for it ? Or update to 0.8.2.0 (which we can make work with scala 2.11. Better, but still not 2.12 so not sure it works with JDK 17) ? Or something else ?

**Comment by tisonkun** [comment]
> That's weird. It compiles fine on my machine... The Spark version used is very old and there could be an incompatibility with JDK17

@cbornet May I ask how this issue resolved finally? Since the change is force pushed it cannot be referred now.

**Pull request merged**
